config/routes.rb
Onlinecoach::Application.routes.draw do
  devise_for :users

  devise_for :installs

 get 'about' => 'pages#about'
 get 'services' => 'pages#services'
 root :to => 'pages#home'

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
         :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  	#content
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
		<div class="footer">
				<small>
					<%= link_to "Online Coach","http://www.adriennejohnston.me" %> by Adrienne Johnston.
				</small>
		</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
        <%= link_to "Online Coach", root_path, class: "brand"%>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
	      	<ul class="nav">
	     			 <li><%= link_to "Home",root_path %></li>
	     			 <li><%= link_to "About",about_path %></li>
             <li><%= link_to "Services",services_path %></li>
   			 </ul>
         <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile",edit_user_registration_path %></li>
               <li><%= link_to "Logout",destroy_user_session_path, method: :delete %></li>
             <% else %>
               <li><%= link_to "Login",new_user_session_path %></li>
          <% end %>
         </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Online Coaching</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
			
		<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "Online Coach", "http://adriennejohnston.me" %>
	is a project to provide online coaching at an affordable price point.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="hero-unit">
			<div class="container">
					<h1>Go to your next assignment!</h1>
				</div>		
		</div>
	<% else %>
		<div class="hero-unit">
			<div class="container">

				<h1>Welcome to Online Coach!</h1>
				<p>
					You have found the home page for 
					<%= link_to "Online Coach", "http://www.adriennejohnston.me" %>
					application.
				</p>
				<p>
				<%= link_to "Sign Up Now!",new_user_registration_path,class: "btn btn-primary btn-large" %>
				</p>
			<p></p>
			<p></p>
			<p></p>
		</div>		
		</div>
		<% end %>

app/views/pages/services.html.erb
Test